# -*- coding: utf-8 -*-
"""Chest X-Ray Abnormality Detector using Transfer Learning (DenseNet121)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gd6ApbD6lQJxWR7GRcUOfS0_A8r8_qKY
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install torch torchvision timm grad-cam streamlit opencv-python kaggle

import torch
print("PyTorch Version:",torch.__version__)
print("GPU Available:",torch.cuda.is_available())
if torch.cuda.is_available():
  print("GPU Name:",torch.cuda.get_device_name(0))

from google.colab import files
files.upload()

!mkdir -p ~ /.kaggle
!cp kaggle.json ~ /.kaggle/
!chmod 600 ~ /.kaggle/kaggle.json

!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

!unzip chest-xray-pneumonia.zip

import os
print(os.listdir("/content/chest_xray"))

import matplotlib.pyplot as plt
from PIL import Image
import os

normal_path = "/content/chest_xray/train/NORMAL"
pneumonia_path = "/content/chest_xray/train/PNEUMONIA"

normal_img= Image.open(os.path.join(normal_path, os.listdir(normal_path)[0]))
pneumonia_img = Image.open(os.path.join(pneumonia_path, os.listdir(pneumonia_path)[0]))

plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
plt.imshow(normal_img,cmap="gray")
plt.title("Normal")
plt.axis("off")
plt.subplot(1,2,2)
plt.imshow(pneumonia_img,cmap="gray")
plt.axis("off")
plt.title("PNEUMONIA")
plt.show()

from torchvision import transforms

train_transform = transforms.Compose([transforms.Resize((224,224)),transforms.RandomHorizontalFlip(),transforms.RandomRotation(10),transforms.ToTensor(),
                                      transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])
test_transform = transforms.Compose([transforms.Resize((224,224)),transforms.ToTensor(),transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])

from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader

train_dataset = ImageFolder("/content/chest_xray/train",transform=train_transform)
val_dataset = ImageFolder("/content/chest_xray/val",transform=test_transform)
test_dataset = ImageFolder("/content/chest_xray/test",transform=test_transform)

train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
val_loader = DataLoader(val_dataset,batch_size=32,shuffle=False)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=False)

print("Train Images:",len(train_dataset))
print("Val Images:",len(val_dataset))
print("Test Images:",len(test_dataset))

import torch
import torch.nn as nn
from torchvision import models

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = models.densenet121(weights=models.DenseNet121_Weights.DEFAULT)
print(model)

# Freeze all pretrained layers

for param in model.parameters():
  param.requires_grad = False

  # Replace classifier
  model.classifier = nn.Sequential(
      nn.Linear(1024,512),
      nn.ReLU(),
      nn.Dropout(0.4),
      nn.Linear(512,2))
  model = model.to(device)
  print(model.classifier)

import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer =optim.Adam(model.classifier.parameters(),lr=0.001)
print("Loss Function:",criterion)
print("optimizer:",optimizer)

num_epochs =5
for epoch in range(num_epochs):
  model.train()
  running_loss=0.0
  correct =0
  total =0
  for images, labels in train_loader:
    images = images.to(device)
    labels = labels.to(device)
    optimizer.zero_grad()
    outputs = model(images)
    loss= criterion(outputs,labels)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
    _, predicted = torch.max(outputs,1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
  train_accuracy = 100*correct/total

  print(f"Epoch {epoch+1}/{num_epochs}")
  print(f"Loss: {running_loss:.4f}")
  print(f"Training Accuracy:{train_accuracy:2f}%")

import os
import torch
#Folder create
os.makedirs("/content/drive/MyDrive/chest_xray_Project",exist_ok=True)
#Model save
torch.save(model.state_dict(),"/content/drive/MyDrive/chest_xray_Project/chest_xray_densenet121.pth")
print("Model Successfully Saved")

model.eval()
correct =0
total =0
with torch.no_grad():
  for images, labels in val_loader:
    images = images.to(device)
    labels = labels.to(device)
    outputs = model(images)
    _, predicted = torch.max(outputs,1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
val_accuracy = 100*correct/total
print(f"Validation Accuracy:{val_accuracy:2f}%")

model.eval()
correct =0
total =0
with torch.no_grad():
  for images, labels in test_loader:
    images = images.to(device)
    labels = labels.to(device)
    outputs = model(images)
    _, predicted = torch.max(outputs,1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
test_accuracy = 100*correct/total
print(f"Test Accuracy:{test_accuracy:2f}%")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

y_true = []
y_pred =[]
model.eval()
with torch.no_grad():
  for images, labels in test_loader:
    images = images.to(device)
    labels = labels.to(device)
    outputs = model(images)
    _, predicted = torch.max(outputs,1)
    y_true.extend(labels.cpu().numpy())
    y_pred.extend(predicted.cpu().numpy())

cm = confusion_matrix(y_true,y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=["NORMAL","PNEUMONIA"])
disp.plot(cmap="Blues")
plt.show()

from sklearn.metrics import roc_curve,auc
import matplotlib.pyplot as plt
import torch.nn.functional as F
y_true = []
y_pred = []
y_score = []
model.eval()
with torch.no_grad():
  for images, labels in test_loader:
    images = images.to(device)
    outputs = model(images)
    probabilities = F.softmax(outputs,dim=1)
    y_true.extend(labels.numpy())
    y_score.extend(probabilities[:,1].cpu().numpy())
fpr, tpr, _ = roc_curve(y_true,y_score)
roc_auc = auc(fpr,tpr)
plt.figure(figsize=(6,6))
plt.plot(fpr,tpr, label=f"AUC={roc_auc:.2f}")
plt.plot([0,1],[0,1],"--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend
plt.show()
print ("AUC Score:", roc_auc)

from google.colab import files
files.download("app.py")